-- @description ADFX Effects
-- @version 1.0.1
-- @author ADFXSound
-- @metapackage
-- @provides
--   [effect] Effects/ADFXHelper; pitch shifter.jsfx > ADFXHelper; pitch shifter.jsfx
--   [effect] Effects/ADFX_Recorder_Capture.jsfx > ADFX_Recorder_Capture.jsfx
--   [effect] Effects/ADFX_SLayer_Trigger.jsfx > ADFX_SLayer_Trigger.jsfx
--   [effect] Effects/ADFX_Varispeed.jsfx > ADFX_Varispeed.jsfx
--   [effect] Effects/ADFX_LOGO_BG_BANNER_CLEAR.png > ADFX_LOGO_BG_BANNER_CLEAR.png
--   [effect] Effects/ADFX_O_LOGO.png > ADFX_O_LOGO.png
--   [effect] Effects/ADFX_PITCH_SHIFTER_LOGO.png > ADFX_PITCH_SHIFTER_LOGO.png
