--about README.md
--amend
--commit-template "index: $changelog

[ci skip]"

--ignore "ADFX/ADFX_Recorder_Demo.lua"
--ignore "ADFX/Modules/ADFX_Recorder.lua"
--ignore "ADFX/Modules/ADFX_Recorder_Buffer.lua"
--ignore "ADFX/Modules/ADFX_Recorder_Engine.lua"
--ignore "ADFX/Modules/ADFX_Recorder_SlotIn.lua"
--ignore "ADFX/Modules/ADFX_Recorder_Util.lua"
--ignore "ADFX/ADFX Renamer Tool/ADFX_Helper; renamer tool.lua"
--ignore "ADFX/ADFX S-Layer/ADFX_S-Layer.lua"
--ignore "ADFX/ADFX Strip Silence/ADFX_Helper; strip silence.lua"
--ignore "ADFX/ADFXHelper Sound Design Pad/ADFX_Helper; sound design pad.lua"
--ignore "ADFX/ADFXHelper Sound Design Pad/ADFX_Tab to Previous Transient.lua"
--ignore "ADFX/ADFXHelper Sound Design Pad/ADFX_Tab to Transient.lua"
