-- @description ADFX Recorder Modules
-- @version 1.0.1
-- @author ADFXSound
-- @metapackage
-- @provides
--   [nomain] Modules/ADFX_Recorder.lua
--   [nomain] Modules/ADFX_Recorder_Buffer.lua
--   [nomain] Modules/ADFX_Recorder_Engine.lua
--   [nomain] Modules/ADFX_Recorder_SlotIn.lua
--   [nomain] Modules/ADFX_Recorder_Util.lua
